config/routes.rb
Rails.application.routes.draw do
  get '/', to: redirect('/books')
  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy'
  put '/bayar/:id', to: 'orders#bayar', as: 'bayar'
  resources :categories
  resources :books
  resources :orders
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
  has_many :orders
  has_many :users, through: :orders 
end

app/models/category.rb
class Category < ApplicationRecord
has_many :books, dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  has_many :books, through: :orders 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def authenticate_user
    if session[:user_id]
      # set current user object to @current_user object variable
      @current_user = User.find session[:user_id]
      true
    else
      redirect_to '/login'
      false
    end
  end
  def authenticate_admin
    if session[:user_id]
      # set current user object to @current_user object variable
      @current_user = User.find session[:user_id]
      if @current_user.role ==1
      true
      else
      false
      end

    else
      redirect_to '/login'
      false
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_admin, only: [:new, :edit, :update, :destroy]
  def new
    @book = Book.new
  end
  def edit
    @book = Book.find(params[:id])
  end
  def update
  @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to @book
    else
      render 'edit'
    end
  end
  def create

    @book = Book.new(book_params)

    if @book.save
      redirect_to @book
    else
      render 'new'
    end
  end
  def index
  # if session[:user_id].present?
  #   @user = User.find(session[:user_id])
  #   @articles = @user.articles.all
  # else
    @books = Book.all
  # end
  end
  def show
  @book = Book.find(params[:id])
end
def destroy
  @book = Book.find(params[:id])
  @book.destroy

  redirect_to book_path
end
  private
  def book_params
    params.require(:book).permit(:nama, :penerbit, :stok,:category_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :authenticate_admin, only: [:new, :edit, :update, :destroy]
    def new
      @category = Category.new
    end
    def edit
      @category = Category.find(params[:id])
    end
    def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to @category
    else
      render 'edit'
    end
    end
    def create

      @category = Category.new(category_params)

      if @category.save
        redirect_to @category
      else
        render 'new'
      end
    end
    def show
      @category = Category.find(params[:id])
    end
    def index

        @categories = Category.all

    end
    def destroy
      @category = Category.find(params[:id])
      @category.destroy

      redirect_to categories_path
    end
    private
      def category_params
        params.require(:category).permit(:nama)
      end
  end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user
  def new
    @order=Order.new
  end

  def create
    tgl_ambil =Date.today
    tgl_sampai = Date.new params[:order]["tanggal_sampai(1i)"].to_i,params[:order]["tanggal_sampai(2i)"].to_i, params[:order]["tanggal_sampai(3i)"].to_i
    @user = User.find(session[:user_id])
    @book = Book.find(params[:order][:books_id])
    @order=Order.create status: 'Dipinjam', tanggal_ambil: tgl_ambil, tanggal_sampai: tgl_sampai, book: @book,user: @user

    if @order.save
      @book.update_attribute(:stok, @book.stok - 1)
      redirect_to '/orders'
    else
      render 'new'
    end
  end
  def bayar
  @order = Order.find(params[:id])

  @order.update_attribute(:denda, 0)
      redirect_to '/orders'
  end
  def index
  # if session[:user_id].present?
  #   @user = User.find(session[:user_id])
  #   @articles = @user.articles.all
  # else
   if session[:admin].present?
    @orders = Order.all
  else 
    @orders =@current_user.orders
  end

  # end
  end
  def edit
    @order = Order.find(params[:id])
  end
  def update
    tgl_balik = Date.today
  @orders = Order.find(params[:id])
  @book = Book.find(@orders.book_id)
  tgl_str1= @orders.tanggal_sampai.to_s
  tgl_str2= tgl_balik.to_s

  tgldue = Date.parse(tgl_str1)
  tgl_back = Date.parse(tgl_str2)

  telat= (tgldue..tgl_back).to_a
    if tgldue < tgl_back
      harga=(telat.length-1)*2000
    else
      harga=0
    end
  @book.update_attribute(:stok, @book.stok + 1)
    if @orders.update(status: "Sudah Kembali" , tanggal_dibalikin: tgl_balik ,denda: harga)
      redirect_to '/orders'
    else
      redirect_to '/books'
    end
  end
  private
  def order_params
    params.require(:order).permit(:tanggal_ambil, :tanggal_sampai, :books_id)
  end


end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user.present? && user.password == params[:session][:password]
      # Log the user in and redirect to the user's show page.
      session[:user_id] = user.id
      if user.role ==1
        session[:admin] = user.id
      end
      redirect_to '/books'
    else
      # Create an error message.
      render 'new'
    end
  end

  def destroy
    reset_session
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  @user = User.new
end
def update
@user = User.find(params[:id])

  if @user.update_attribute(:role, 1)
    redirect_to '/login'
  end
end
def create
  @user = User.new(user_params)

  if @user.save
    redirect_to '/login'
  else
    render 'new'
  end
end

def show
  @user = User.find(params[:id])
end

private

def user_params
  params.require(:user).permit(:email, :password, :fullname, :alamat)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with(model: @book, local: true) do |form| %>

  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@book.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :nama %><br>
    <%= form.text_field :nama %>
  </p>

  <p>
    <%= form.label :penerbit %><br>
    <%= form.text_field :penerbit %>
  </p>
  <p>
    <%= form.label :stok %><br>
    <%= form.number_field :stok %>
  </p>
  <p>
  <%= form.select(:category_id, options_from_collection_for_select(Category.all, :id, :nama)) %>

  </p>
  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>
<%= render 'form' %>

<%= link_to 'Back', book_path %>

app/views/books/index.html.erb
<h1>Listing articles</h1>
<% if session[:user_id].present? %>
<%= link_to 'Logout', logout_path,
        method: :delete,
        data: { confirm: 'Are you sure?' } %>|
<% if session[:admin].present? %><%= link_to 'New Books', new_book_path %>
|
<%= link_to 'New Category', new_category_path %>|<% end %>
<%= link_to 'Lihat Buku yang Anda Pinjam', orders_path %>|
<% else %>
<%= link_to 'Login', login_path %>|
<% end %>

<table>
  <tr>
    <th>Judul</th>
    <th>Penerbit</th>
    <th>Stok</th>
    <th>Category</th>
    <th></th>
  </tr>

  <% @books.each do |book| %>
    <tr>
      <td><%= book.nama %></td>
      <td><%= book.penerbit %></td>
      <td><%= book.stok %></td>
      <td><%= book.category.nama %></td>
      <td><% if book.stok>0 %><%= link_to 'Pinjam', new_order_path(book: book.id) %>  <% end %></td>
      <td><%= link_to 'Show', book_path(book) %></td>
      <% if session[:admin].present? %>
      <td><%= link_to 'Edit', edit_book_path(book) %></td>
      <td><%= link_to 'Destroy', book_path(book),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
      <% end %>
  <% end %>
</table>

app/views/books/new.html.erb
<h1>New Books</h1>
<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p>
  <strong>Judul:</strong>
  <%= @book.nama %>
</p>

<p>
  <strong>Penerbit:</strong>
  <%= @book.penerbit %>
</p>
<p>
  <strong>Stok:</strong>
  <%= @book.stok %>
</p>
<p>
  <strong>Category:</strong>
  <%= @book.category.nama %>
</p>


<% if session[:admin].present? %>
<%= link_to 'Edit', edit_book_path(@book) %> |
<% end %>
<%= link_to 'Back', books_path %>

app/views/categories/_form.html.erb
<%= form_with(model: @category, local: true) do |form| %>

  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@category.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :nama %><br>
    <%= form.text_field :nama %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>
<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing Categories</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>

  <% @categories.each do |category| %>
    <tr>
      <td><%= category.nama %></td>
      <td><%= link_to 'Show', category_path(category) %></td>
      <% if session[:user_id].present? %>
      <td><%= link_to 'Edit', edit_category_path(category) %></td>
      <td><%= link_to 'Destroy', category_path(category),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
      <% end %>
  <% end %>
</table>

app/views/categories/new.html.erb
<h1>New Category</h1>
<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p>
  <strong>Nama:</strong>
  <%= @category.nama %>
</p>
<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BINARBatch11BeCodeChallange</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/edit.html.erb
<%= form_with(model: @order, local: true) do |form| %>

  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@order.errors.count, "error") %> prohibited
        this order from being saved:
      </h2>
      <ul>
        <% @order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <p>
    <%= form.label :tanggal_dibalikin %><br>
    <%= form.date_select :tanggal_dibalikin %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/orders/index.html.erb
<h1>List Peminjaman Anda</h1>
<% if session[:user_id].present? %>
<%= link_to 'Logout', logout_path,
        method: :delete,
        data: { confirm: 'Are you sure?' } %>|
<%= link_to 'Daftar Buku', books_path %>|
<% end %>
<table>
  <tr>
    <td>Status</td>
    <td>Tanggal Meminjam</td>
    <td>Tanggal Harus Mengembalikan:</td>
<% if session[:admin].present? %>
    <td>Nama Peminjam:</td>
<% end %>
    <td>Judul Buku:</td>
    <td>Tanggal Mengembalikan:</td>
    <td>Harga Denda:</td>
    <td></td>

  </tr>
<% @orders.each do |order| %>
  <tr>
    <td><%= order.status %></td>
    <td><%= order.tanggal_ambil %></td>
    <td><%= order.tanggal_sampai %></td>
<% if session[:admin].present? %>
    <td><%= order.user.fullname %></td>
<% end %>
    <td><%= order.book.nama %></td>
    <td><%= order.tanggal_dibalikin %></td>
    <% if order.status =="Sudah Kembali" %>
    <td><%= order.denda %></td><% end %>
    <td></td><% if order.status =="Dipinjam" %>
    <td><%= link_to 'Kembalikan', order_path(order) ,
            method: :patch,
            data: { confirm: 'Are you sure?' } %></td><% end %>
    <% if order.denda != 0  %>
    <% if order.denda != nil  %>
    <td><%= link_to 'Bayar Denda', bayar_path(order) ,
                    method: :put,
                    data: { confirm: 'Are you sure?' } %></td><% end %><% end %>


  </tr>
<% end %>
</table>

app/views/orders/new.html.erb
<%= form_with(model: @order, local: true) do |form| %>

  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@order.errors.count, "error") %> prohibited
        this order from being saved:
      </h2>
      <ul>
        <% @order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :tanggal_ambil %><br>
    <%= form.date_select :tanggal_ambil ,selected: Date.today , :disabled => true %>
  </p>

  <p>
    <%= form.label :tanggal_sampai %><br>
    <%= form.date_select :tanggal_sampai %>
  </p>
    <p>
      <%= form.hidden_field :books_id,:value => params[:book] %>
    </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/session/new.html.erb
<% if session[:user_id].present? %>

<%= controller.redirect_to '/books' %>
<% end %>
<% provide(:title, "Log in") %>
<h1>Log in</h1>


    <%= form_for(:session, url: login_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>

    <p>New user? <%= link_to "Sign up now!", new_user_path %></p>

app/views/users/new.html.erb
<h1>Login</h1>
<%= form_with(model: @user, local: true) do |form| %>

  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>
  <p>
    <%= form.label :password %><br>
    <%= form.password_field :password %>
  </p>
  <p>
    <%= form.label :fullname %><br>
    <%= form.text_field :fullname %>
  </p>
  <p>
    <%= form.label :alamat %><br>
    <%= form.text_area :alamat %>
  </p>
  <p>
    <%= form.submit %>
  </p>

<% end %>
<%= link_to 'Back', books_path %>

app/views/users/show.html.erb
<p>
  <strong>Nama:</strong>
  <%= @user.fullname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>
<p>
  <strong>Alamat:</strong>
  <%= @user.alamat %>
</p>
<%= link_to 'Jadikan Admin', user_path(@user) ,
        method: :put,
        data: { confirm: 'Are you sure?' } %>